apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-poc-api-config
data:
  APP_ENV: base
  API_VERSION: v1
  LOG_LEVEL: info
  API_PORT: "8080"
  PAYMENT_GATEWAY_URL: "http://payment-gateway"
  TRANSACTION_TIMEOUT: "30"