apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-poc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-poc-api
  template:
    metadata:
      labels:
        app: payment-poc-api
    spec:
      containers:
      - name: payment-poc-api
        image: payment-poc-api:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: payment-poc-api-config