apiVersion: v1
kind: ConfigMap
metadata:
  name: integration-api-config
data:
  APP_ENV: base
  API_VERSION: v1
  LOG_LEVEL: info
  API_PORT: "8080"
  INTEGRATION_ENDPOINT: "http://integration-service"
  DB_PASSWORD: "GjhsjhshÂ§$4@@hdhj"